# --- colorscheme
[[plugins]]
repo = 'sainnhe/gruvbox-material'
hook_add = '''
    let g:gruvbox_material_transparent_background = 1
    set background=dark
    colorscheme gruvbox-material
'''

# --- ale
[[plugins]]
repo = 'dense-analysis/ale'
hook_add = '''
    let g:ale_disable_lsp = 1
    let g:ale_linters = {
    \ 'cs' : ['OmniSharp']
    \}

    " nmap <silent> gan :ALENext<cr>
    " nmap <silent> gab :ALEPrevious<cr>
'''

# --- airline
[[plugins]]
repo = 'vim-airline/vim-airline'
[[plugins]]
repo = 'vim-airline/vim-airline-themes'
hook_add = '''
    " Powerline系フォントを利用する
    set laststatus=2
    let g:airline_powerline_fonts = 1
    " タブ移動左右
    let g:airline#extensions#tabline#enabled = 1
    nmap <S-h> <Plug>AirlineSelectPrevTab
    nmap <S-l> <Plug>AirlineSelectNextTab
    let g:airline#extensions#tabline#buffer_idx_mode = 1
    let g:airline#extensions#tabline#formatter = 'unique_tail'
    let g:airline_theme = 'gruvbox_material'
    if !exists('g:airline_symbols')
      let g:airline_symbols = {}
    endif

    " unicode symbols
    let g:airline_left_sep = '»'
    let g:airline_left_sep = '▶'
    let g:airline_right_sep = '«'
    let g:airline_right_sep = '◀'
    let g:airline_symbols.crypt = '🔒'
    let g:airline_symbols.linenr = '☰'
    let g:airline_symbols.linenr = '␊'
    let g:airline_symbols.linenr = '␤'
    let g:airline_symbols.linenr = '¶'
    let g:airline_symbols.maxlinenr = ''
    let g:airline_symbols.maxlinenr = '㏑'
    let g:airline_symbols.branch = '⎇'
    let g:airline_symbols.paste = 'ρ'
    let g:airline_symbols.paste = 'Þ'
    let g:airline_symbols.paste = '∥'
    let g:airline_symbols.spell = 'Ꞩ'
    let g:airline_symbols.notexists = '∄'
    let g:airline_symbols.whitespace = 'Ξ'

    " powerline symbols
    let g:airline_left_sep = ''
    let g:airline_left_alt_sep = ''
    let g:airline_right_sep = ''
    let g:airline_right_alt_sep = ''
    let g:airline_symbols.branch = ''
    let g:airline_symbols.readonly = ''
    let g:airline_symbols.linenr = '☰'
    let g:airline_symbols.maxlinenr = ''
'''

# --- accelerated-smooth-scroll
# [[plugins]]
# repo = 'yonchu/accelerated-smooth-scroll'
# hook_add = '''
#     let g:ac_smooth_scroll_du_sleep_time_msec = 5
#     let g:ac_smooth_scroll_fb_sleep_time_msec = 5
# '''

# --- easymotion
[[plugins]]
repo = 'easymotion/vim-easymotion'
hook_add = '''
    map , <leader>
    map ,, <leader><leader>s
    map <leader>s <Plug>(easymotion-bd-f2)
    nmap <leader>s <Plug>(easymotion-overwin-f2)
    map <leader>l <Plug>(easymotion-bd-jk)
    nmap <leader>l <Plug>(easymotion-overwin-line)

    let g:EasyMotion_smartcase = 1
'''

# --- nvim-tree
# nvim-treeにフォーカスした状態で g? でキーマップ確認
[[plugins]]
repo = 'nvim-tree/nvim-web-devicons'
[[plugins]]
repo = 'nvim-tree/nvim-tree.lua'
hook_add = '''
nnoremap <silent> <F2> :NvimTreeFindFileToggle<CR>

lua << EOF
-- disable netrw at the very start of your init.lua (strongly advised)
vim.g.loaded_netrw = 1
vim.g.loaded_netrwPlugin = 1

-- set termguicolors to enable highlight groups
vim.opt.termguicolors = true

-- setup with some options
require("nvim-tree").setup({
  -- remove_keymapsがないとかでエラー出るようになってたのでキーバインド変更をCO

  -- '-'キーを無効化し、'u'で階層を上がるように(tmux用nvim-treeとバインドを同じにするため)
--  view = {
--    mappings = {
--      list = {
--        { key = "u", action = "dir_up" },
--      },
--    },
--  },
--  remove_keymaps = {
--    '-',
--  }
})

-- nvim-treeが最後のbufferだった場合、自動で閉じる(参考:https://github.com/nvim-tree/nvim-tree.lua/wiki/Auto-Close)
vim.api.nvim_create_autocmd("BufEnter", {
  nested = true,
  callback = function()
    if #vim.api.nvim_list_wins() == 1 and require("nvim-tree.utils").is_nvim_tree_buf() then
      vim.cmd "quit"
    end
  end
})
EOF
'''

# --- neosnippet-snippets
[[plugins]]
repo = 'Shougo/neosnippet-snippets'

# --- auto-pairs
[[plugins]]
repo = 'jiangmiao/auto-pairs'

# --- fzf
[[plugins]]
repo = 'junegunn/fzf.vim'
hook_add = '''
    " fzfのリポジトリへpathを通しておく必要がある (参考: https://github.com/junegunn/fzf.vim/issues/439#issuecomment-1268535686 )
    set rtp+=/opt/homebrew/Cellar/fzf/*/


    "nnoremap <C-p> :call FzfOmniFiles()<cr>
    nnoremap <C-p> :Files<cr>
    nnoremap <C-g> :Rg<cr>

    " fzf (C-p)
    "fun! FzfOmniFiles()
    "  let is_git = system('git status')
    "    if v:shell_error
    "        :Files
    "    else
    "        :GitFiles
    "    endif
    "endfun

    " ripgrep (C-g)
    if executable('rg')
        command! -bang -nargs=* Rg
        \ call fzf#vim#grep(
        \ 'rg --column --line-number --hidden --ignore-case --no-heading --color=always '.shellescape(<q-args>), 1,
        \ <bang>0 ? fzf#vim#with_preview({'options': '--delimiter : --nth 4..'}, 'up:60%')
        \ : fzf#vim#with_preview({'options': '--delimiter : --nth 4..'}, 'right:50%:hidden', '?'),
        \ <bang>0)
    endif
'''

# --- vim-gitgutter
[[plugins]]
repo = 'airblade/vim-gitgutter'
hook_add = '''
    nnoremap ghn :GitGutterNextHunk<cr>:GitGutterPreviewHunk<cr>
    nnoremap ghb :GitGutterPrevHunk<cr>:GitGutterPreviewHunk<cr>
    nnoremap ghs :GitGutterStageHunk<cr>
    nnoremap ghu :GitGutterUndoHunk<cr>
    nnoremap ghp :GitGutterPreviewHunk<cr>
'''

# --- indentLine
#[[plugins]]
#repo = 'Yggdroot/indentLine'
#hook_add = '''
#    "let g:indentLine_char = '⮞'
#    let g:indentLine_char = '▏'
#'''

# --- vim-brightest
# [[plugins]]
# repo = 'osyo-manga/vim-brightest'
# hook_add = '''
#     let g:brightest#highlight = {
#     \    "group" : "BrightestUnderLine"
#     \ }
# '''

# --- coc.nvim
[[plugins]]
repo = 'neoclide/coc.nvim'
merged = '0'
rev = 'release'
hook_add = '''
    nmap <silent> gd <Plug>(coc-definition)
    nmap <silent> gy <Plug>(coc-type-definition)
    nmap <silent> gi <Plug>(coc-implementation)
    nmap <silent> gr <Plug>(coc-references)
    nnoremap <silent> == :call CocAction('format')<CR>
    nnoremap <silent> ghh :call <SID>show_documentation()<CR>

    nmap <silent> <A-Enter> <Plug>(coc-codeaction-cursor)
    " for mac (Altキーが使えないため)
    nmap <silent> g<Enter> <Plug>(coc-codeaction-cursor)

    nmap <silent> gan <Plug>(coc-diagnostic-next)
    nmap <silent> gab <Plug>(coc-diagnostic-prev)
    nmap <silent> <Space>r <Plug>(coc-rename)

    function! s:show_documentation()
        if (index(['vim','help'], &filetype) >= 0)
            execute 'h '.expand('<cword>')
        else
            call CocAction('doHover')
        endif
    endfunction

    " autocomplete (参考: https://qiita.com/totto2727/items/d0844c79f97ab601f13b)
    inoremap <silent><expr> <C-j> coc#pum#visible() ? coc#pum#next(1) : "\<C-j>"
    inoremap <silent><expr> <C-k> coc#pum#visible() ? coc#pum#prev(1) : "\<C-k>"
    inoremap <silent><expr> <Enter> coc#pum#visible() ? coc#pum#confirm() : "\<Enter>"
    "inoremap <silent><expr> <Esc> coc#pum#visible() ? coc#pum#cancel() : "\<Esc>" " ← なくてもEscで閉じるようになっている

    " <Tab>で次、<S+Tab>で前
    inoremap <silent><expr> <TAB>
    \ coc#pum#visible() ? coc#pum#next(1):
    \ <SID>check_back_space() ? "\<Tab>" :
    \ coc#refresh()
    inoremap <expr><S-TAB> coc#pum#visible() ? coc#pum#prev(1) : "\<S-TAB>" " "\<C-h>"
    inoremap <silent><expr> <c-space> coc#refresh()
'''

# --- vim-polyglot
[[plugins]]
repo = 'sheerun/vim-polyglot'

# --- tagbar
[[plugins]]
repo = 'preservim/tagbar'
hook_add = '''
    nmap <silent> <F3> :TagbarToggle<CR>
'''

# --- vim-startify
# [[plugins]]
# repo = 'mhinz/vim-startify'
# hook_add = '''
#     let g:startify_change_to_dir = 0
#     let g:startify_change_to_vcs_root = 0
# '''

# --- vim-commentary
[[plugins]]
repo = 'tpope/vim-commentary'
hook_add = '''
    noremap <silent> <Space>/ :Commentary<CR>

    " Ctrl+/ は<C-/>じゃない (https://qiita.com/castaneai/items/42e917d1fdf6d83b717c)
    noremap <silent> <C-_> :Commentary<CR>
'''

# --- vim-table-mode
# 使い方
# 1. :TableModeToggleでOn
# 2. |name|address|phone|のように入力
# 3. ||を入力するとセパレーターが追加される
# 4. 次の行以降、手順2で入力していく
[[plugins]]
repo = 'dhruvasagar/vim-table-mode'
hook_add = '''
    let g:table_mode_corner = '+'
    let g:table_mode_corner_corner = '|'
    let g:table_mode_header_fillchar = '='
'''

# --- vim-devicons
[[plugins]]
repo = 'ryanoasis/vim-devicons'
hook_add = '''
    let g:WebDevIconsUnicodeDecorateFolderNodes = 1
'''

# --- AmbiCompletion
[[plugins]]
repo = 'vim-scripts/AmbiCompletion'


# ==== nvimでgoのデバッグ環境構築 (https://zenn.dev/saito9/articles/32c57f776dc369) ====
# 他にDelveが必要なので 'go install github.com/go-delve/delve/cmd/dlv@latest' をコマンドライン実行して取得
# --- nvim-dap
[[plugins]]
repo = 'mfussenegger/nvim-dap'
hook_add = '''
  source ~/nvim-dap.lua
'''
# --- nvim-nio
# nvim-dap-uiに必要
[[plugins]]
repo = 'nvim-neotest/nvim-nio'
# --- nvim-dap-ui
[[plugins]]
repo = 'rcarriga/nvim-dap-ui'
# --- nvim-treesitter
# dap-virtual-text用に必要
[[plugins]]
repo = 'nvim-treesitter/nvim-treesitter'
# --- nvim-dap-virtual-text
# デバッグ中変数の値を表示してくれるプラグイン
# 1. gccが必要となってくるためchocoでmingwを入れる。
# 2. nvim上で :TSInstall go を実行して言語をインストール
# (また :TSInstallInfo を実行すれば、インストール可能な言語名とそのインストール状態が確認できる)
[[plugins]]
repo = 'theHamsta/nvim-dap-virtual-text'
# --- nvim-dap-go
[[plugins]]
repo = 'leoluz/nvim-dap-go'
# ==== ここまで: nvimでgoのデバッグ環境構築 ====


# --- vim-visual-multi
# ctrl + n: カーソル下の単語を検索対象とし、マルチカーソルモードに入る
#     n: 次の単語にジャンプし選択状態に
#     N: 前の単語にジャンプし選択状態に
#     ]: 選択状態の次の単語にジャンプ
#     [: 選択状態の前の単語にジャンプ
#     q: 最後に選択したものを選択解除し、次の単語にジャンプし選択状態に
#     Q: 最後に選択したものを選択解除し、選択状態の前の単語にジャンプ
# ctrl + up/down: カーソル位置からマルチカーソルモードに入る
# (マルチカーソル操作中に) Tab: 選択範囲操作/カーソル位置操作 切り替え
[[plugins]]
repo = 'mg979/vim-visual-multi'

